name: DTU_ML_Ops
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - pip
    - dvc
    - pip:
          - setuptools==69.0.3
          - dvc-gs==3.0.1
          - torch==2.0.1
          - torchvision==0.15.2
          - torchaudio==2.0.2
          - optuna==3.4
          - torch_tb_profiler==0.4.3
          - torchdata==0.6.1
          - torchtext==0.15.2
          - pytorch_lightning==2.0.2
          - pytorch_forecasting==1.0.0
          - rich==13.7.0
          - pytest==7.4.4
          - wandb==0.16.1
          - numpy==1.26.3
          - matplotlib==3.8.2
          - pandas==2.1.4
          - pyarrow==14.0.2
          - fastparquet==2023.10.1
          - coverage==7.4.0
          - soundfile==0.12.1
          - gcloud==0.18.3
          - google-api-python-client==2.113.0
          - click==8.1.7
          - omegaconf==2.3.0
          - google-cloud-storage==2.14.0
          - google-cloud-secret-manager==2.17.0
          - fastapi==0.109.0
          - uvicorn==0.26.0
          - fastapi-restful[all]
