site_name: Wheel_Assembly_Detection
site_author: DTU
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - Improvements: improvements.md
  - List of Commands: commands.md
  - Docker Notes: docker.md
  - Project Summary: summary.md
  - Slack Canva: todo.md
