name: Build and Deploy our model to Cloud Run

env:
    DOCKER_BUILDKIT: 1
    IMAGE_NAME: served_model
    REGION: europe-west1
    CLOUD_RUN_SERVICE_NAME: deployed-model-service
    CLOUD_RUN_REGION: europe-west1
    SERVICE_ACCOUNT: github-sa@wheel-assembly-detection.iam.gserviceaccount.com

on:
    push:
        branches:
            - serve-model-cloud-run

jobs:
    build-and-deploy-model:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            # Restore Docker build cache
            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ env.IMAGE_NAME }}-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-${{ env.IMAGE_NAME }}-
                      ${{ runner.os }}-buildx-

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GCP
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: "${{ secrets.GCP_SA_KEY }}"

            - name: Set up GCP Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: ${{ secrets.GCP_PROJECT }}

            - name: Configure Docker for GCP Artifact Registry
              run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

            - name: Build and Push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: dockerfiles/deploy_model.dockerfile
                  tags: ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/wheel-assembly-detection-images/${{ env.IMAGE_NAME }}:latest
                  push: true
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache-new

            # Save Docker build cache
            - name: Save Docker cache
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache-new
                  key: ${{ runner.os }}-buildx-${{ env.IMAGE_NAME }}-${{ github.sha }}

            - name: Deploy to Cloud Run
              uses: google-github-actions/deploy-cloudrun@v0
              with:
                  service: ${{ env.CLOUD_RUN_SERVICE_NAME }}
                  image: ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/wheel-assembly-detection-images/${{ env.IMAGE_NAME }}:latest
                  region: ${{ env.CLOUD_RUN_REGION }}
                  credentials: ${{ secrets.GCP_SA_KEY }}
