name: Build, Push Docker Training Image and Run Vertex AI Job

env:
    IMAGE_NAME: train_model
    REGION: europe-west1
    DISPLAY_NAME: train-model:${{ github.sha }}
    VERTEX_CONFIG_PATH: src/models/config/vertex_config.yaml

on:
    push:
        branches:
            - main
jobs:
    train-build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GCP Artifact Registry
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: "${{ secrets.GCP_SA_KEY }}"

            - name: Set up GCP Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: ${{ secrets.GCP_PROJECT }}

            - name: Configure Docker for GCP Artifact Registry
              run: gcloud auth configure-docker europe-west1-docker.pkg.dev

            - name: Build and Push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: dockerfiles/train_model.dockerfile
                  tags: europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/wheel-assembly-detection-images/${{env.IMAGE_NAME}}:latest
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache
                  push: true

            - name: Run Vertex AI Custom Job
              run: |
                  gcloud ai custom-jobs create \
                    --region=${{ env.REGION }} \
                    --display-name=${{ env.DISPLAY_NAME }} \
                    --config=${{ env.VERTEX_CONFIG_PATH }}
