name: Run data pytest on pull request
on:
  pull_request:
    branches:
      - main  # Add the branch you want to trigger the workflow

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.9  # Set the Python version you need
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          dvc pull
          pip install -e .

      - name: Run pytest
        run: |
          pytest --disable-warnings

      - name: Run pytest with coverage
        uses: lpenz/ghaction-pytest-cov@v1

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
