name: Run data pytest on pull request
on:
  push:
    branches:
      - main  # Add the branch you want to trigger the workflow

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GCP
        uses: google-github-actions/auth@v2
        with:
            credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
            project_id: ${{ secrets.GCP_PROJECT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.9  # Set the Python version you need
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          dvc pull
          pip install -e .

      - name: Run tests and collect coverage
        run: pytest --disable-warnings --cov=api.calculator --cov-report=xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}