name: Read requirements.txt and mirror the packages to Conda environment.yml
on:
  pull_request:
    branches:
      - main  # Add the branch you want to trigger the workflow

jobs:
  test:
    name: Mirror Requirements.txt to Environment.yml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.9  # Set the Python version you need
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          dvc pull
          pip install -e .

      - name: Generate environment.yml
        run: python src/helper/convert_reqs_to_env.py

      - name: Commit and push if changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add environment.yml
          git commit -m "Update environment.yml" || exit 0  # Commit only if there are changes
          git push origin ${{ github.event.ref }}
